### ISSUE TITLE
mkmf hash not valid

### ISSUE THREAD

**Issue by raphaeldussin** [ESMG/ESMG-configs#14]
```git submodule update```fails on mkmf with the error:

> error: Server does not allow request for unadvertised object 8aa71a24c0891618e7d6c4d45fca9468e3a9948f
Fetched in submodule path 'src/mkmf', but it did not contain 8aa71a24c0891618e7d6c4d45fca9468e3a9948f. Direct fetching of that commit failed.

**Comment by raphaeldussin** [comment]
it seems that this hash does not point to anything anymore.

@kshedstrom @MJHarrison-GFDL @adcroft do we have a procedure to update submodule hash?

**Comment by kshedstrom** [comment]
I still do not grok the submodules. I had the same failure when checking everything out again after the recent filesystem failure and I don't know how to fix it. I went into src/mkmf and got it checked out to my "master" and all is well - except that ESMG-configs didn't see that as a change to track.
